version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-container
    ports:
      - "8080:80"
    volumes:
      - "D:/mit-projekt:/var/www/html"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spilteori
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "D:/mysql-data:/var/lib/mysql"

volumes:
  mysql-data: